// @vitest-environment jsdom
import{beforeEach,describe,expect,it,vi}from'vitest';import{flushPromises,mount}from'@vue/test-utils';import ElementPlus from'element-plus';import Manager from'./Manager.vue';import{listEndpoints,listSubscriptions,createEndpoint,createSubscription,updateEndpoint,updateEndpointSchedule}from'../../api/integration';import{listObjectTypes}from'../../api/mdm';
vi.mock('../../api/integration',()=>({listEndpoints:vi.fn(),listSubscriptions:vi.fn(),createEndpoint:vi.fn(),createSubscription:vi.fn(),updateEndpoint:vi.fn(),updateEndpointSchedule:vi.fn()}));vi.mock('../../api/mdm',()=>({listObjectTypes:vi.fn()}));
describe('integration subscriptions',()=>{beforeEach(()=>{vi.clearAllMocks();localStorage.setItem('user',JSON.stringify({is_admin:true}));localStorage.setItem('permissions','[]');listEndpoints.mockResolvedValue({data:[{id:1,code:'ERP'}]});listSubscriptions.mockResolvedValue({data:[]});listObjectTypes.mockResolvedValue({data:[{id:2,code:'person',name:'个人信息'}]});createSubscription.mockResolvedValue({data:{id:3}})});
it('loads choices and creates a scoped subscription payload',async()=>{const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();await w.get('[data-test="subscription-endpoint"]').trigger('click');w.vm.subscription.endpoint_id=1;w.vm.subscription.object_type_id=2;w.vm.subscription.event_type='RECORD_CHANGED';await w.get('[data-test="create-subscription"]').trigger('click');await flushPromises();expect(listObjectTypes).toHaveBeenCalled();expect(createSubscription).toHaveBeenCalledWith({endpoint_id:1,object_type_id:2,event_type:'RECORD_CHANGED'});expect(listSubscriptions).toHaveBeenCalledTimes(2);});
it('hides management controls when field-manage permission is not editable',async()=>{localStorage.setItem('user',JSON.stringify({is_admin:false}));localStorage.setItem('permissions',JSON.stringify([{code:'MDM_FIELD_MANAGE',can_edit:false}]));const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();expect(w.find('[data-test="subscription-endpoint"]').exists()).toBe(false);expect(w.find('[data-test="create-subscription"]').exists()).toBe(false);});
it('submits BASIC credentials without retaining them in the form',async()=>{createEndpoint.mockResolvedValue({data:{id:4,code:'ERP',authentication_type:'BASIC',credentials_configured:true}});const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();expect(w.get('[data-test="authentication-type"]').exists()).toBe(true);w.vm.endpoint.code='ERP';w.vm.endpoint.name='ERP';w.vm.endpoint.endpoint_url='https://example.com/hooks';w.vm.endpoint.authentication_type='BASIC';w.vm.endpoint.username='delivery-user';w.vm.endpoint.password='delivery-password';await w.get('[data-test="create-endpoint"]').trigger('click');await flushPromises();expect(createEndpoint).toHaveBeenCalledWith({code:'ERP',name:'ERP',endpoint_url:'https://example.com/hooks',authentication_type:'BASIC',credentials:{username:'delivery-user',password:'delivery-password'}});expect(w.vm.endpoint.password).toBe('');expect(w.text()).not.toContain('delivery-password');});
it('renders only the selected BEARER or API key credential inputs',async()=>{const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();w.vm.endpoint.authentication_type='BEARER';await w.vm.$nextTick();expect(w.find('[data-test="bearer-token"]').exists()).toBe(true);expect(w.find('[data-test="basic-username"]').exists()).toBe(false);w.vm.endpoint.authentication_type='API_KEY';await w.vm.$nextTick();expect(w.find('[data-test="api-key-header"]').exists()).toBe(true);expect(w.find('[data-test="api-key-value"]').exists()).toBe(true);expect(w.find('[data-test="bearer-token"]').exists()).toBe(false);});
it('edits an endpoint without requiring or exposing its stored credential',async()=>{listEndpoints.mockResolvedValue({data:[{id:1,code:'ERP',name:'旧 ERP',endpoint_url:'https://old.example/hook',authentication_type:'BEARER',credentials_configured:true,status:'active'}]});updateEndpoint.mockResolvedValue({data:{id:1}});const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();await w.get('[data-test="edit-endpoint-1"]').trigger('click');expect(w.vm.endpoint.code).toBe('ERP');expect(w.vm.endpoint.token).toBe('');w.vm.endpoint.name='新 ERP';w.vm.endpoint.endpoint_url='https://new.example/hook';await w.get('[data-test="create-endpoint"]').trigger('click');await flushPromises();expect(updateEndpoint).toHaveBeenCalledWith(1,{name:'新 ERP',endpoint_url:'https://new.example/hook',authentication_type:'BEARER'});expect(w.text()).not.toContain('existing-encrypted-value');});
it('configures a six-field cron and timezone without exposing credentials',async()=>{listEndpoints.mockResolvedValue({data:[{id:1,code:'ERP',name:'ERP',endpoint_url:'https://example.com/hook',authentication_type:'BEARER',credentials_configured:true,status:'active',schedule_enabled:false}]});updateEndpointSchedule.mockResolvedValue({data:{id:1,schedule_enabled:true}});const w=mount(Manager,{global:{plugins:[ElementPlus]}});await flushPromises();await w.get('[data-test="schedule-endpoint-1"]').trigger('click');w.vm.schedule.enabled=true;w.vm.schedule.cron='0 30 9 * * *';w.vm.schedule.timezone='Asia/Shanghai';await w.get('[data-test="save-schedule"]').trigger('click');await flushPromises();expect(updateEndpointSchedule).toHaveBeenCalledWith(1,{enabled:true,cron:'0 30 9 * * *',timezone:'Asia/Shanghai'});expect(w.text()).toContain('定时策略');expect(w.text()).not.toContain('existing-encrypted-value');});
});
