package com.simplemdm.service.integration;
import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.ObjectMapper;import com.simplemdm.exception.BusinessException;import com.simplemdm.model.integration.*;import com.simplemdm.model.mdm.MdmRecord;import com.simplemdm.repository.integration.*;import com.simplemdm.repository.mdm.MdmRecordRepository;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service("relationalPushService")
public class PushService {
 private static final ObjectMapper JSON=new ObjectMapper();private final PushSubscriptionRepository subscriptions;private final PushLogRepository logs;private final MdmRecordRepository records;private final int snapshotLimit;
 public PushService(PushSubscriptionRepository subscriptions,PushLogRepository logs,MdmRecordRepository records,@Value("${simple-mdm.push.snapshot-limit:2000}")int snapshotLimit){this.subscriptions=subscriptions;this.logs=logs;this.records=records;this.snapshotLimit=Math.max(128,Math.min(2000,snapshotLimit));}
 @Transactional public void publishRecordChanged(Long recordId){MdmRecord r=records.findById(recordId).orElseThrow(()->new BusinessException(404,"Record not found"));String eventId="record:"+r.getId()+":version:"+r.getVersion();String snapshot=snapshot(r);List<PushSubscription> matching=subscriptions.findActiveForEvent(r.getSystemId(),r.getObjectTypeId(),"RECORD_CHANGED");for(PushSubscription s:matching)logs.insertPendingIfAbsent(r.getSystemId(),s.getId(),r.getId(),eventId,snapshot);}
 private String snapshot(MdmRecord r){String code=Objects.toString(r.getRecordCode(),"");int points=code.codePointCount(0,code.length());for(int keep=points;keep>=0;keep--){String shortened=code.substring(0,code.offsetByCodePoints(0,keep));String json=write(envelope(r,shortened));if(json.length()<=snapshotLimit)return json;}String minimal=write(Map.of("record_id",r.getId(),"version",r.getVersion()));if(minimal.length()<=snapshotLimit)return minimal;throw new IllegalStateException("Push snapshot limit cannot fit minimal envelope");}
 private Map<String,Object> envelope(MdmRecord r,String code){Map<String,Object> value=new LinkedHashMap<>();value.put("record_id",r.getId());value.put("system_id",r.getSystemId());value.put("object_type_id",r.getObjectTypeId());value.put("department_id",r.getDepartmentId());value.put("version",r.getVersion());value.put("record_code",code);return value;}
 private String write(Object value){try{return JSON.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalStateException("Cannot serialize push snapshot",e);}}
}