package com.simplemdm.controller;
import com.simplemdm.exception.GlobalExceptionHandler;import com.simplemdm.model.system.User;import com.simplemdm.repository.*;import com.simplemdm.repository.integration.*;import com.simplemdm.repository.mdm.*;import com.simplemdm.repository.system.UserRepository;import com.simplemdm.repository.workflow.*;import com.simplemdm.security.*;import com.simplemdm.service.system.AuthorizationService;import com.simplemdm.service.workflow.ApprovalService;import org.junit.jupiter.api.*;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import java.util.*;
import static org.mockito.BDDMockito.given;import static org.mockito.Mockito.*;import static org.springframework.http.MediaType.APPLICATION_JSON;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class HttpSecurityContractTest{JwtUtil jwt=new JwtUtil("01234567890123456789012345678901",60);UserRepository users=mock(UserRepository.class);PushEndpointRepository endpoints=mock(PushEndpointRepository.class);PushSubscriptionRepository subscriptions=mock(PushSubscriptionRepository.class);PushLogRepository logs=mock(PushLogRepository.class);ApprovalRequestRepository approvals=mock(ApprovalRequestRepository.class);AuthorizationService auth=mock(AuthorizationService.class);MockMvc mvc;User user;
@BeforeEach void setup(){user=mock(User.class);given(user.getId()).willReturn(7L);given(user.getSystemId()).willReturn(10L);given(user.isActive()).willReturn(true);given(users.findById(7L)).willReturn(Optional.of(user));var integration=new IntegrationController(endpoints,subscriptions,logs,mock(ObjectTypeRepository.class),auth);var workflow=new WorkflowController(approvals,mock(ApprovalChangeRepository.class),mock(FieldDefinitionRepository.class),mock(ApprovalService.class),auth);mvc=MockMvcBuilders.standaloneSetup(integration,workflow).addInterceptors(new JwtInterceptor(jwt,users,mock(SysUserRepository.class))).setControllerAdvice(new GlobalExceptionHandler()).build();}
String bearer(){return "Bearer "+jwt.createToken(7L,10L);}
@Test void rejectsUnauthenticatedWorkflowAndIntegration()throws Exception{mvc.perform(get("/api/workflow/approvals")).andExpect(status().isUnauthorized());mvc.perform(get("/api/integration/endpoints")).andExpect(status().isUnauthorized());}
@Test void rejectsPermissionDeniedOverRealInterceptorPath()throws Exception{given(user.isSystemAdmin()).willReturn(false);given(auth.can(anyLong(),anyString(),any())).willReturn(false);mvc.perform(post("/api/integration/endpoints").header("Authorization",bearer()).contentType(APPLICATION_JSON).content("{\"code\":\"ERP\",\"name\":\"ERP\",\"endpoint_url\":\"https://erp.example\",\"authentication_type\":\"NONE\"}")).andExpect(status().isForbidden());}
@Test void listQueriesOnlyCurrentSystemAndDoesNotLeakSnapshots()throws Exception{given(user.isSystemAdmin()).willReturn(true);var log=mock(com.simplemdm.model.integration.PushLog.class);given(log.getRequestSnapshot()).willReturn("{secret:true}");given(logs.findBySystemIdOrderByIdDesc(10L)).willReturn(List.of(log));mvc.perform(get("/api/integration/logs").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString("request_snapshot"))));verify(logs).findBySystemIdOrderByIdDesc(10L);}
@Test void regularViewerCannotReadSnapshotButAdminCan()throws Exception{var log=mock(com.simplemdm.model.integration.PushLog.class);given(log.getRequestSnapshot()).willReturn("{secret:true}");given(logs.findBySystemIdAndId(10L,5L)).willReturn(Optional.of(log));given(user.isSystemAdmin()).willReturn(false);given(auth.can(7L,"MDM_RECORD_VIEW",null)).willReturn(true);mvc.perform(get("/api/integration/logs/5").header("Authorization",bearer())).andExpect(status().isForbidden());given(user.isSystemAdmin()).willReturn(true);mvc.perform(get("/api/integration/logs/5").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(jsonPath("$.data.request_snapshot").value("{secret:true}"));}
@Test void crossSystemApprovalIsNotFound()throws Exception{given(user.isSystemAdmin()).willReturn(true);given(approvals.findBySystemIdAndId(10L,99L)).willReturn(Optional.empty());mvc.perform(get("/api/workflow/approvals/99").header("Authorization",bearer())).andExpect(status().isNotFound());verify(approvals).findBySystemIdAndId(10L,99L);}
}