package com.simplemdm.controller;
import com.simplemdm.exception.GlobalExceptionHandler;import com.simplemdm.model.system.User;import com.simplemdm.repository.integration.*;import com.simplemdm.repository.mdm.ObjectTypeRepository;import com.simplemdm.security.JwtInterceptor;import com.simplemdm.service.system.AuthorizationService;import org.junit.jupiter.api.*;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import java.util.Optional;
import static org.mockito.BDDMockito.given;import static org.mockito.Mockito.*;import static org.springframework.http.MediaType.APPLICATION_JSON;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
class IntegrationControllerTest {PushEndpointRepository endpoints;ObjectTypeRepository objects;MockMvc mvc;
@BeforeEach void setUp(){endpoints=mock(PushEndpointRepository.class);objects=mock(ObjectTypeRepository.class);var user=mock(User.class);given(user.getId()).willReturn(7L);given(user.getSystemId()).willReturn(10L);given(user.isSystemAdmin()).willReturn(true);JwtInterceptor.CURRENT_USER.set(user);mvc=MockMvcBuilders.standaloneSetup(new IntegrationController(endpoints,mock(PushSubscriptionRepository.class),mock(PushLogRepository.class),objects,mock(AuthorizationService.class))).setControllerAdvice(new GlobalExceptionHandler()).build();}
@AfterEach void clean(){JwtInterceptor.CURRENT_USER.remove();}
@Test void rejectsMissingAndMalformedEndpointFields()throws Exception{mvc.perform(post("/api/integration/endpoints").contentType(APPLICATION_JSON).content("{\"code\":\"\",\"name\":\"x\",\"endpoint_url\":\"not-url\",\"authentication_type\":\"NONE\"}")).andExpect(status().isBadRequest());mvc.perform(post("/api/integration/endpoints").contentType(APPLICATION_JSON).content("{")).andExpect(status().isBadRequest());verifyNoInteractions(endpoints);}
@Test void rejectsUrlWithoutHttpHost()throws Exception{mvc.perform(post("/api/integration/endpoints").contentType(APPLICATION_JSON).content("{\"code\":\"x\",\"name\":\"x\",\"endpoint_url\":\"http://\",\"authentication_type\":\"NONE\"}")).andExpect(status().isBadRequest());}
@Test void rejectsInvalidSubscriptionAndCrossSystemObjectType()throws Exception{mvc.perform(post("/api/integration/subscriptions").contentType(APPLICATION_JSON).content("{\"endpoint_id\":1,\"object_type_id\":2,\"event_type\":\"EVIL\"}")).andExpect(status().isBadRequest());given(endpoints.findBySystemIdAndId(10L,1L)).willReturn(Optional.of(mock()));mvc.perform(post("/api/integration/subscriptions").contentType(APPLICATION_JSON).content("{\"endpoint_id\":1,\"object_type_id\":2,\"event_type\":\"RECORD_CHANGED\"}")).andExpect(status().isNotFound());}
}