package com.simplemdm.controller;
import com.simplemdm.dto.ApiResponse;import com.simplemdm.exception.BusinessException;import com.simplemdm.model.integration.*;import com.simplemdm.model.system.User;import com.simplemdm.repository.integration.*;import com.simplemdm.repository.mdm.ObjectTypeRepository;import com.simplemdm.security.JwtInterceptor;import com.simplemdm.service.system.AuthorizationService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/integration")
public class IntegrationController{
 private final PushEndpointRepository endpoints;private final PushSubscriptionRepository subscriptions;private final PushLogRepository logs;private final ObjectTypeRepository objectTypes;private final AuthorizationService auth;
 public IntegrationController(PushEndpointRepository e,PushSubscriptionRepository s,PushLogRepository l,ObjectTypeRepository o,AuthorizationService a){endpoints=e;subscriptions=s;logs=l;objectTypes=o;auth=a;}
 @GetMapping("/endpoints") public ApiResponse endpoints(){User u=viewUser();return ApiResponse.ok(endpoints.findBySystemIdOrderByCode(u.getSystemId()).stream().map(EndpointView::of).toList());}
 @PostMapping("/endpoints") public ApiResponse endpoint(@Valid @RequestBody EndpointBody b){User u=manageUser();return ApiResponse.ok(EndpointView.of(endpoints.save(PushEndpoint.create(u.getSystemId(),b.code(),b.name(),b.endpoint_url(),b.authentication_type()))));}
 @GetMapping("/subscriptions") public ApiResponse subscriptions(){User u=viewUser();return ApiResponse.ok(subscriptions.findBySystemIdOrderByIdDesc(u.getSystemId()).stream().map(SubscriptionView::of).toList());}
 @PostMapping("/subscriptions") public ApiResponse subscription(@Valid @RequestBody SubscriptionBody b){User u=manageUser();endpoints.findBySystemIdAndId(u.getSystemId(),b.endpoint_id()).orElseThrow(()->new BusinessException(404,"Endpoint not found"));objectTypes.findBySystemIdAndId(u.getSystemId(),b.object_type_id()).orElseThrow(()->new BusinessException(404,"Object type not found"));return ApiResponse.ok(SubscriptionView.of(subscriptions.save(PushSubscription.active(null,u.getSystemId(),b.endpoint_id(),b.object_type_id(),b.event_type()))));}
 @GetMapping("/logs") public ApiResponse logs(){User u=viewUser();return ApiResponse.ok(logs.findBySystemIdOrderByIdDesc(u.getSystemId()).stream().map(LogView::of).toList());}
 private User viewUser(){return require("MDM_RECORD_VIEW");}private User manageUser(){return require("MDM_FIELD_MANAGE");}
 private User require(String p){User u=JwtInterceptor.CURRENT_USER.get();if(u==null)throw new BusinessException(401,"System user required");if(!u.isSystemAdmin()&&!auth.can(u.getId(),p,u.getDepartmentId()))throw new BusinessException(403,"Permission required");return u;}
 public record EndpointBody(@NotBlank @Size(max=64) String code,@NotBlank @Size(max=128) String name,@NotBlank @Pattern(regexp="https?://.+") String endpoint_url,@NotBlank @Pattern(regexp="NONE|BASIC|BEARER") String authentication_type){}
 public record SubscriptionBody(@NotNull Long endpoint_id,@NotNull Long object_type_id,@NotBlank @Pattern(regexp="RECORD_CHANGED|RECORD_CREATED|RECORD_UPDATED|RECORD_DELETED") String event_type){}
 public record EndpointView(Long id,String code,String name,String endpoint_url,String authentication_type,String status){static EndpointView of(PushEndpoint e){return new EndpointView(e.getId(),e.getCode(),e.getName(),e.getEndpointUrl(),e.getAuthenticationType(),e.getStatus());}}
 public record SubscriptionView(Long id,Long endpoint_id,Long object_type_id,String event_type,String status){static SubscriptionView of(PushSubscription s){return new SubscriptionView(s.getId(),s.getEndpointId(),s.getObjectTypeId(),s.getEventType(),s.getStatus());}}
 public record LogView(Long id,Long subscription_id,Long record_id,String event_id,String status,Integer retry_count,String request_snapshot){static LogView of(PushLog l){return new LogView(l.getId(),l.getSubscriptionId(),l.getRecordId(),l.getEventId(),l.getStatus(),l.getRetryCount(),l.getRequestSnapshot());}}
}