package com.simplemdm.controller;
import com.simplemdm.dto.ApiResponse; import com.simplemdm.exception.BusinessException; import com.simplemdm.model.mdm.*; import com.simplemdm.model.system.User; import com.simplemdm.model.workflow.*; import com.simplemdm.repository.mdm.FieldDefinitionRepository; import com.simplemdm.repository.workflow.*; import com.simplemdm.security.JwtInterceptor; import com.simplemdm.service.mdm.UpdateRecordCommand; import com.simplemdm.service.system.AuthorizationService; import com.simplemdm.service.workflow.ApprovalService; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/workflow/approvals")
public class WorkflowController {
 private final ApprovalRequestRepository requests; private final ApprovalChangeRepository changes; private final FieldDefinitionRepository fields; private final ApprovalService service; private final AuthorizationService auth;
 public WorkflowController(ApprovalRequestRepository r,ApprovalChangeRepository c,FieldDefinitionRepository f,ApprovalService s,AuthorizationService a){requests=r;changes=c;fields=f;service=s;auth=a;}
 @GetMapping public ApiResponse list(){User u=user();return ApiResponse.ok(requests.findBySystemIdOrderByIdDesc(u.getSystemId()).stream().filter(x->can(u,"MDM_RECORD_VIEW",x.getDepartmentId())).map(this::view).toList());}
 @GetMapping("/{id}") public ApiResponse detail(@PathVariable Long id){User u=user();ApprovalRequest x=scoped(id,u);return ApiResponse.ok(detailView(x));}
 @PostMapping("/submit") public ApiResponse submit(@RequestBody SubmitBody b){User u=user();Long id=service.submit(new UpdateRecordCommand(u.getSystemId(),b.object_type_id,b.record_id,b.department_id,b.expected_version,b.data),u.getId());return ApiResponse.ok(Map.of("id",id));}
 @PostMapping("/{id}/approve") public ApiResponse approve(@PathVariable Long id){User u=user();ApprovalRequest x=scoped(id,u);if(!can(u,"APPROVAL_REVIEW",x.getDepartmentId()))throw new BusinessException(403,"Approval permission required");return ApiResponse.ok(service.approve(id,u.getId(),x.getExpectedVersion()));}
 private ApprovalRequest scoped(Long id,User u){ApprovalRequest x=requests.findBySystemIdAndId(u.getSystemId(),id).orElseThrow(()->new BusinessException(404,"Approval not found"));if(!can(u,"MDM_RECORD_VIEW",x.getDepartmentId()))throw new BusinessException(403,"Approval not visible");return x;}
 private boolean can(User u,String p,Long d){return u.isSystemAdmin()||auth.can(u.getId(),p,d);}
 private User user(){User u=JwtInterceptor.CURRENT_USER.get();if(u==null)throw new BusinessException(401,"System user required");return u;}
 private Map<String,Object> view(ApprovalRequest x){Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("object_type_id",x.getObjectTypeId());m.put("record_id",x.getRecordId());m.put("department_id",x.getDepartmentId());m.put("requested_by",x.getRequestedBy());m.put("expected_version",x.getExpectedVersion());m.put("status",x.getStatus());return m;}
 private Map<String,Object> detailView(ApprovalRequest x){Map<Long,FieldDefinition> defs=new HashMap<>();fields.findAllById(changes.findByApprovalRequestId(x.getId()).stream().map(ApprovalChange::getFieldDefinitionId).toList()).forEach(f->defs.put(f.getId(),f));Map<String,Object> m=view(x);m.put("changes",changes.findByApprovalRequestId(x.getId()).stream().map(c->{FieldDefinition f=defs.get(c.getFieldDefinitionId());Map<String,Object> v=new LinkedHashMap<>();v.put("field_key",f==null?null:f.getFieldKey());v.put("field_name",f==null?null:f.getFieldName());v.put("data_type",f==null?null:f.getDataType().name());v.put("old_value",scalar(c.oldValue()));v.put("new_value",scalar(c.newValue()));return v;}).toList());return m;}
 private Object scalar(TypedValue v){if(v.stringValue()!=null)return v.stringValue();if(v.textValue()!=null)return v.textValue();if(v.integerValue()!=null)return v.integerValue();if(v.decimalValue()!=null)return v.decimalValue();if(v.booleanValue()!=null)return v.booleanValue();if(v.dateValue()!=null)return v.dateValue();if(v.datetimeValue()!=null)return v.datetimeValue();return v.referenceRecordId();}
 public static class SubmitBody {public Long object_type_id;public Long record_id;public Long department_id;public long expected_version;public Map<String,Object> data;}
}